bar: {background: '', bottom: 'false', font0: 'DejaVu Sans Mono:size=10:antialias=false;2',
  height: 20, radius: 0, width: 100%}
border: {all: 0, bottom: 0, color: '', pixels: 2, top: 0}
gap: {inner: 20, outer: 0}
terminal:
  background: ''
  bold: ''
  colors: ['', '', '', '', '', '', '', '', '']
  font: Share Tech Mono 10
  foreground: ''
  termbackground: ''
wallpaper: {saved: /usr/share/backgrounds/any.jpg}
